

def on_tpm_give_up(details):
    import logging
    from ib_common.constants.exception_messages import RETRY_AGAIN

    logger = logging.getLogger(__name__)
    logger.warning('Boto Retry give up', extra={'stack': True})

    from django_swagger_utils.drf_server.exceptions import BadRequest
    raise BadRequest(*RETRY_AGAIN)
